#!/bin/bash

set -x
SOURCE="$1"
AWKNAME="$2"
BASENAME=$(basename "$SOURCE" .h)
TDIR="snippets"
TARGET="$TDIR/$BASENAME".md

# generate page
mkdir -p "$TDIR"
curl -s https://raw.githubusercontent.com/DCC-EX/CommandStation-EX/refs/heads/$SOURCE | awk -f "pull-${AWKNAME}.awk" > "$TARGET"

# make footer
cat <<EOF >> "$TARGET"

## Build info:

EOF
echo -n "Autogenerated from $SOURCE at " >> "$TARGET"
date >> "$TARGET"

# debug
#git diff | head -100 # just to check if something changed

exit 0


