#!/bin/bash

SOURCE=devel/EXRAIL2MacroBase.h
BASENAME=$(basename "$SOURCE" .h)
TDIR="snippets/exrail"
TARGET="$TDIR/$BASENAME".md
mkdir -p "$TDIR"
curl -s https://raw.githubusercontent.com/DCC-EX/CommandStation-EX/refs/heads/$SOURCE | awk -f pull-exrail.awk > "$TARGET"
echo -n "Autogenerated from $SOURCE at " >> "$TARGET"
date >> "$TARGET"

exit 0


