#!/bin/bash

set -x
SOURCE=devel/DCCEXCommands.h
BASENAME=$(basename "$SOURCE" .h)
TDIR="snippets"
TARGET="$TDIR/$BASENAME".md
mkdir -p "$TDIR"
curl -s https://raw.githubusercontent.com/DCC-EX/CommandStation-EX/refs/heads/$SOURCE | awk -f pull-cmdref.awk > "$TARGET"
echo -n "Autogenerated from $SOURCE at " >> "$TARGET"
date >> "$TARGET"
git diff
git commit -m 'overwrite' -a
exit 0


