nav:
  - Contributing to Documentation: index.md
  - Working with GitHub: github.md
  - Documentation Standards: standards.md
  - Formatting Guide: formatting-guide.md
  - Understanding Links: understanding-links.md
  - Using Our Logos: logos.md
  - Working With ProperDocs: mkdocs-features.md
  - Mermaid Diagrams: mermaid-diagrams.md
