nav:
  - Product List: products.md
  - Getting Started: getting-started.md
  - EX-CommandStation: ex-commandstation
  - EX-MotorShield8874: ex-motorshield8874
  - EX-WiFiShield8266: ex-wifishield8266
  - EX-FastClock: ex-fastclock
  - EX-IOExpander: ex-ioexpander
  - EX-Turntable: ex-turntable
  - EX-SensorCAM: ex-sensorcam
  - "*"
