nav:
  - Build Your Own: diy.md
  - Selecting a Power Supply: power.md
  - Easy Build - Arduino Mega: mega-easy.md
  - Harder Build - Arduino Mega: mega-harder.md
  - Complex Build - Nucleo: nucleo.md
  - Complex Build - ESP32: esp32.md
  - Optional WiFi: wifi.md
  - Optional Ethernet: ethernet.md
  - Installing Software: installer.md
  - Other Devices: others.md
