nav:
  - Build Your Own: diy.md
  - Easy Build<small> - Arduino Mega + EX-8874</small>: mega-easy.md
  - Harder Build<small> - Arduino Mega + Arduino Motor Shield</small>: mega-harder.md
  - Complex Build<small> - Nucleo</small>: nucleo.md
  - Complex Build<small> - ESP32</small>: esp32.md
  - Selecting a Power Supply: power.md
  - <br/>Optional WiFi: wifi.md
  - Optional Ethernet: ethernet.md
  - <br/>Install &amp; Configure Software: installer.md
  - Configure WiFi <small><small>(EX-CSB1 & ESP32 v5.7.0+)</small></small>: config-wifi-esp32.md
  - Testing your EX-CommandStation: testing.md
  - <br/>Other Devices: others.md
