nav:
  - Throttles:
    - Throttle Lists: throttles.md
    - Some Recommended Throttles:
      - EX-WebThrottle (Web): ex-webthrottle.md
      - Engine Driver (Android): engine-driver.md
      - ThrottleCard (iOS): throttlecard.md
    - WiThrottle VS Native Protocol: withrottle-vs-native-protocol.md
  - Loco/CV Programming: cv-programming.md
  
