nav:
  - EX-SensorCAM: ex-sensorcam.md
  - Installation Guide: installation-guide.md
  - User Manual: ex-sensor-manual.md
  - Command Reference: ex-sensorcam-command-reference.md
  - Manual Abridged: ex-sensor-manual-abridged.md
