nav:
  - Ex Sensorcam: ex-sensorcam.md
  - Installation Guide: installation-guide.md
  - Ex Sensor Manual: ex-sensor-manual.md
  - Ex Sensorcam Command Reference: ex-sensorcam-command-reference.md
  - Ex Sensor Manual Abridged: ex-sensor-manual-abridged.md
