nav:
  - Accessories: accessories.md
  - Actuators: actuators.md
  - Sensors: sensors.md
  - Servo Turnouts/Points: connecting-servo-turnout.md
  - Hardware List: hardware-list.md
  - I2C (I<sup>2</sup>C) Intro: i2c-intro.md
  - Buying I2C (I<sup>2</sup>C) Devices: buying-i2c-devices.md
  - Various Devices: various-devices
