nav:
  - EX-CommandStation Overview: overview.md
  - <b>EX-CSB1 CommandStation/Booster 1 Express</b>: ex-csb1.md
  - Configuration <small>(config.h)</small>: config-h.md
  - Configure WiFi <small>(Wifi Shield)</small>: config-wifi-shield.md
  - Configure WiFi <small>(CSB1 & ESP32 v5.7.0+)</small>: config-wifi-esp32.md
  - Testing your EX-CommandStation: testing.md
  - TrackManager: trackmanager
  - Loco Programming: loco-programming
  - Running a DC layout: dc-running.md
  - Accessories: accessories
  - EXRAIL: exrail
