nav:
  - EX-CommandStation: overview.md
  - EX-CSB1 Command Station/Booster: ex-csb1.md
  - Running a DC layout: dc-running.md
  - Configuration (config.h): config-h.md
  - Configure WiFi (Wifi Shield): config-wifi-shield.md
  - Configure WiFi (CSB1 & ESP32 v5.7.0+): config-wifi-esp32.md
  - Testing your EX-CommandStation: testing.md
  - TrackManager: trackmanager
  - Loco Programming: loco-programming
  - Accessories: accessories
  - EXRAIL: exrail
