nav:
  - Defining Dcc Turnouts: defining-dcc-turnouts.md
  - Defining Pin Turnouts: defining-pin-turnouts.md
  - Defining Servo Turnouts: defining-servo-turnouts.md
  - Facing Turnouts: facing-turnouts.md
  - Animated Turnouts: animated-turnouts.md
  - Toggle With Button: toggle-with-button.md
