nav:
  - Defining Dcc Turnouts/Points: defining-dcc-turnouts.md
  - Defining Pin Turnouts/Points: defining-pin-turnouts.md
  - Defining Servo Turnouts/Points: defining-servo-turnouts.md
  - Facing Turnouts/Points: facing-turnouts.md
  - Animated Turnouts/Points: animated-turnouts.md
  - Toggle With Button: toggle-with-button.md
