nav:
  - Overview: overview.md
  - Hardware: hardware.md
  - Calibration: calibration.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Operation: operation.md
  - Timecontrol: timecontrol.md
