nav:
  - Signal basics: index.md
  - LED signals: led-signals.md
  - Neopixel signals: products/ex-commandstation/exrail/cookbooks/neopixels/signals.md
  - Flashing Signals: flashing-signals.md
  - Semaphore signals: semaphore-signals.md
  - DCC Signals: dcc-signals.md
