nav:
  - Home: index.md
  - Products: products
  - Purchase: purchasing
  - Install: installer
  - Self Build: diy
  - Throttles: throttles
  - News: news
  - Support: support
  - Donate: donations
  - Reference : reference
  - About Us: about
  - Contribute: contributing
  - Contents: toc_not_in_nav.md
  