nav:
  - Home: index.md
  - Products: products
  - Purchase: purchasing
  - Self Build: diy
  - Install: installer
  - Throttles: throttles
  - News: news
  - Support: support
  - Reference : reference
  - About Us: about
  - Donate / Contribute: contributing
  - ToC: toc.md
  