nav:
  - How You Can Contribute: contributing.md
  - User Journeys: user-journeys.md
  - Release Checklist: release-checklist.md
  - Contributing Code: code/contributing-code.md
  - Contributing Documentation: documentation
  