nav:
  - EX-Installer<small><small> (Install &amp; Configure)</small></small>: installer.md
  - First Run: first-run.md
  - Select A Product: select-product.md
  - Install EX-CommandStation: install-cs.md
  - Install EX-IOExpander: install-ex-ioexpander.md
  - Install EX-Turntable<br>: install-ex-turntable.md
  - Download EX-Installer: download
  - Test Your Installation<br>: testing.md
  - <br/>Advanced Users - VSC/PlatformIO: platformio.md
