nav:
  - Using EX-Installer: overview.md
  - Installer: installer.md
  - First Run: first-run.md
  - Select Product: select-product.md
  - Install Cs: install-cs.md
  - Advanced Users - PlatformIO: platformio.md
  - Download linux: download-linux.md
  - Download mac: download-mac.md
  - Download win: download-win.md
