nav:
  - Table of Contents: toc.md
  - Glossary of Terms: glossary.md
  - <br/>Advanced config.h Options: advanced-config-h.md
  - EXRAIL Command List: exrail-command-reference.md
  - <br/>TrackManager: trackmanager
  - <br/>Alternate Microcontrollers: microcontrollers
  - Other Hardware: hardware
  - Wiring: wiring
  - <br/>Throttle Developers: throttle-writers
  - DCC-EX Serial/Native Commands: serial-commands
  - Command Station Internal Architecture: command-station-architecture
  - <i>External References</i>: external-references